# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: gindexer
description: GANChain Indexer
networks:
  - id: 4048
    rpc_config: 
      url: "https://rpc.gpu.net"
    start_block: 0
    contracts:
      - name: ERC20
        handler: src/EventHandlers.ts
        events:
          - event: "Transfer(address indexed from, address indexed to, uint256 value)"
# Unordered multichain mode allows you to index events from multiple chains
# in realtime but doesn't guarentee ordering between chains
# https://docs.envio.dev/docs/HyperIndex/multichain-indexing#unordered-multichain-mode
unordered_multichain_mode: true
